package jflowmap.views;

/**
 * @author Ilya Boyandin
 */
public enum ColorCodes {

  BACKGROUND,

  AREA_PAINT,
  AREA_STROKE,

  NODE_PAINT,
  NODE_HIGHLIGHTED_PAINT,
  NODE_SELECTED_PAINT,
  NODE_STROKE_PAINT,
  NODE_SELECTED_STROKE_PAINT,

  EDGE_STROKE_HIGHLIGHTED_PAINT,
  EDGE_STROKE_HIGHLIGHTED_INCOMING_PAINT,
  EDGE_STROKE_HIGHLIGHTED_OUTGOING_PAINT,

  EDGE_SELF_LOOP_MIN_WEIGHT,
  EDGE_SELF_LOOP_MAX_WEIGHT,

  EDGE_GRADIENT_START_MIN_WEIGHT,
  EDGE_GRADIENT_START_MAX_WEIGHT,
  EDGE_GRADIENT_END_MIN_WEIGHT,
  EDGE_GRADIENT_END_MAX_WEIGHT,

  EDGE_START_MARKER_MIN_WEIGHT,
  EDGE_START_MARKER_MAX_WEIGHT,
  EDGE_END_MARKER_MIN_WEIGHT,
  EDGE_END_MARKER_MAX_WEIGHT,

  EDGE_NO_GRADIENT_MIN_WEIGHT,
  EDGE_NO_GRADIENT_MAX_WEIGHT,

  EDGE_NO_GRADIENT_DIVERGING_MIN,
  EDGE_NO_GRADIENT_DIVERGING_ZERO,
  EDGE_NO_GRADIENT_DIVERGING_MAX,

  LEDGEND_TEXT,
  LEDGEND_BOX_PAINT, LEDGEND_ARROW,

  FLOW_ATTR_LABEL
}
